spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-trading
    username: postgres
    password: FAr3z=G%
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  h2:
    console:
      enabled: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL55Dialect

xtb:
  login: "mocklogin"
  password: "mockpassword"


alpha-vintage: OS9RJPKMNU6UUDLW
